package mx.com.upax.models;
// Generated 22/08/2020 05:31:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeWorkedHours generated by hbm2java
 */
@Entity
@Table(name="employee_worked_hours"
    ,schema="public"
)
public class EmployeeWorkedHours  implements java.io.Serializable {


     private long id;
     private Jobs jobs;
     private short workedHours;
     private Date workedDate;
     private Date createdAt;
     private Date updatedAt;

    public EmployeeWorkedHours() {
    }

    public EmployeeWorkedHours(long id, Jobs jobs, short workedHours, Date workedDate, Date createdAt, Date updatedAt) {
       this.id = id;
       this.jobs = jobs;
       this.workedHours = workedHours;
       this.workedDate = workedDate;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id", nullable=false)
    public Jobs getJobs() {
        return this.jobs;
    }
    
    public void setJobs(Jobs jobs) {
        this.jobs = jobs;
    }

    
    @Column(name="worked_hours", nullable=false)
    public short getWorkedHours() {
        return this.workedHours;
    }
    
    public void setWorkedHours(short workedHours) {
        this.workedHours = workedHours;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="worked_date", nullable=false, length=13)
    public Date getWorkedDate() {
        return this.workedDate;
    }
    
    public void setWorkedDate(Date workedDate) {
        this.workedDate = workedDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=29)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=29)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


